libpsi: Add explicit header files
The libpsi source code is actually missing cutils and stdio header files.
The buggy libspi compiles fine now because the aosp llvm toolchain on system
side is somehow pulling in some more header chains while compiling this lib
which staifies this bug and hence compiles well. But when this library was
exported to vendor side and compiles the source code, we get the following
compilation error:

Starting ninja...
[ 94% 777/824] //system/core/lmkd/libpsi:libpsi clang psi.c [arm]
FAILED: out/soong/.intermediates/system/core/lmkd/libpsi/libpsi/android_arm_armv8-2a_cortex-a75_vendor_static/obj/system/core/lmkd/libpsi/psi.o
system/core/lmkd/libpsi/psi.c:39:10: error: implicit declaration of function 'TEMP_FAILURE_RETRY' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
fd = TEMP_FAILURE_RETRY(open(PSI_MON_FILE_MEMORY, O_WRONLY | O_CLOEXEC));
         ^
system/core/lmkd/libpsi/psi.c:48:15: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned int, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
        res = snprintf(buf, sizeof(buf), "%s %d %d",)
              ^
system/core/lmkd/libpsi/psi.c:48:15: note: include the header <stdio.h> or explicitly provide a declaration for 'snprintf'
system/core/lmkd/libpsi/psi.c:64:30: error: implicit declaration of function 'write' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    res = TEMP_FAILURE_RETRY(write(fd, buf, strlen(buf) + 1));
                             ^
system/core/lmkd/libpsi/psi.c:74:5: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    close(fd);
     ^

This dependency of libpsi on llvm toolchain of system pulling in some
more header chains is wrong and should be independent of toolchain.
Hence, explicitly add cutils and stdio header files, and add
libcutils_headers to the header library in Android.bp.

Bug: 169346507
Change-Id: I2d613d5724d3c5f52dd52dcae7024439f2e8d5bb
Signed-off-by: Sudarshan Rajagopalan <sudaraja@codeaurora.org>